aws_access_key = "demo"
aws_secret_key = "demo"
rds_password   = "demo"
lambda_file = "C:/Users/savit/OneDrive/Documents/aws/Fraud Detection Project/Dev/Fraud_Detection_ETL_project/Lambda Function/fraud_detection_ETL.zip"
lambda_layer_dependencies_file = "C:/Users/savit/OneDrive/Documents/aws/Fraud Detection Project/Dev/Fraud_Detection_ETL_project/my_lambda_layer/fraud_detection_etl_lambda_dependencies.zip"